apiVersion: v1
kind: Service
metadata:
  name: face-sim-pinecone-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007 # You can choose a different port if necessary
  selector:
    app: face-sim-pinecone