apiVersion: v1
kind: Service
metadata:
  name: face-sim-pinecone-service
  labels:
    app: face-sim-pinecone
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: face-sim-pinecone